version: '2'
services:
  bartender:
   build: ./litbit-bartender
   image: litbit-bartender:snapshot
   depends_on:
     - db
   ports:
     - 4567:4567
   networks:
     testing_net:
       ipv4_address: 172.28.1.5


  ui:
   build: ./litbit-ui
   image: litbit-ui:snapshot
   depends_on:
     - bartender
   ports:
     - 8080:80
   networks:
     testing_net:
       ipv4_address: 172.28.1.2

  db: 
    build: ./litbit-mysql
    image: litbit-mysql:snapshot
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drinks
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

networks:
  testing_net:
      ipam:
          driver: default
          config:
            - subnet: 172.28.0.0/16